version: "3.8"

services:

  web:
    build:
      context: ./project
      dockerfile: Dockerfile
      args:
        http_proxy:
        https_proxy:
        socks_proxy:
        DJANGO_CONFIGURATION: 'deploy'
    volumes:
      - ./project:/usr/src/app
    restart: always

  proxy:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./project:/usr/src/app
      - ./proxy/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    links:
      - web
    restart: always