# Generated by Django 2.2.4 on 2021-05-04 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_comment', to='notice.Notice'),
        ),
    ]
